---
- name: Create Temporary Directory
  tempfile:
    state: directory
  register: temp_dir

- name: Download font zip file and save to temporary directory
  get_url:
    url: "{{ font_zip_url }}"
    dest: "{{ temp_dir.path }}/{{ font_zip_url | basename }}"
    mode: 0755 

- name: Create ~/.local/share/fonts/Meslo
  file:
    path: "{{ ansible_user_dir }}/.local/share/fonts/Meslo"
    state: directory
    mode: 0755

- name: Unzip font files to ~/.local/share/fonts/Meslo
  unarchive:
    src: "{{ temp_dir.path }}/{{ font_zip_url | basename }}"
    dest: "{{ ansible_user_dir }}/.local/share/fonts/Meslo"
    
- name: Ensure ~/.config/terminator Directory Exists
  file:
    path: "{{ ansible_user_dir }}/.config/terminator"
    state: directory
    mode: 0755

- name: Copy Terminator config file
  copy:
    src: "terminator_config"
    dest: "{{ ansible_user_dir }}/.config/terminator/config"
    force: yes

- name: Copy .zshrc file
  copy:
    src: ".zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
    force: yes

- name: Delete Temporary Directory
  file:
    path: "{{ temp_dir.path }}"
    state: absent

- name: Check if Powerlevel10k repository exists
  stat:
    path: "{{ ansible_user_dir }}/.powerlevel10k"
  register: powerlevel10k_repo
  
- name: Clone Powerlevel10k repository
  command: "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git {{ ansible_user_dir }}/.powerlevel10k"
  when: powerlevel10k_repo.stat.exists == False

- name: Edit .zshrc file
  lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    line: "source {{ ansible_user_dir }}/.powerlevel10k/powerlevel10k.zsh-theme"
    insertafter: EOF
    state: present