---
- name: Update and upgrade packages
  apt:
    update_cache: true
    upgrade: true
  become: true

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_to_install }}"
  become: true

- name: enable snapd service
  service:
    name: snapd
    enabled: true
    state: started
  become: true

- name: enable snapd apparmor
  service:
    name: apparmor
    enabled: true
    state: started
  become: true

- name: Install Obsidian
  snap:
    name: obsidian
    classic: true
    channel: latest/stable
  become: true